// (C) Emma Litvin, Nicole Quinstedt. Group: 11 (2023)
// Work package 1
// Exercise 3
// Submission code: XXXX

/*------------------------------------------------------------------------------------------
References:
 - Stephen G. Kochan, Programming in C, 4th Edition
-------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------
Exercise 3: Computer creates a random integer number within a range from 1 to 100.
 Program asks the user to enter number. The program keep running and responds to user input
 in two different ways:
 1. if the user guessed the number correctly, the program confirms that the number was
    guessed correctly and prints number of attempts it took to guess the number, or
 2. informs the user if the guess was too low or too high.
 If the user provided the wrong guess, the program will continue running until number of
 guesses exceeds the value of MAX_NUMBER.
-------------------------------------------------------------------------------------------*/

// Include section
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// Define section
#define MAX_NUMBER 13

// Main program section
int main(void) {

    // Variable declaration
    char choice = 'y';   // User input indicating whether to stay in the game

    /* Gives a random function a new seed (i.e., a starting point),
        where time(0) give the time in seconds since the Unix epoch. */
    srand(time(0));

    // Function declaration
    void guess_game();

    // Run the program if the user decides to keep playing after failure
    do {
        // Run the game
        guess_game();
        // Prompt the user to confirm start of another round
        printf("Would you like to try again? Type 'y' if you do.\nYour answer: \n");
        // Read the user choice
        scanf("%s", &choice);
    // Condition to start the game again
    } while (choice == 'y');

    return 0;
}

// Function that runs the game
void guess_game() {

    // Variables declaration
    int guess,           // Number entered by the user
        lower = 1,       // Lower range for generating random number
        upper = 100,     // Upper limit for generating random number
        random,          // Random number generated by the program
        counter = 0;     // Initialize count for number of guesses

    // Program creates random number between 1 and 100
    random = (rand() % (upper - lower + 1)) + lower;

    // Program runs until number of guesses reached MAX_NUMBER or the user guesses the number
    do {
        // Print message to prompt the user to input a number
        printf("Guess the number between 1 and 100: ");
        // Save provided user input into variable 'guess'
        scanf("%i", &guess);

        // Check whether the user input is valid
        if(guess >= lower && guess <= upper) {
            // Increment count of guesses
            counter++;
            // Program compares the user input to generated random number
            if (guess == random) {   // Case if number was guessed correctly
                printf("Your guess is correct! You have guessed %i times.\n\n", counter);
                // Exits the loop
                break;
            } else if (guess < random) {   // Case if the user input is smaller than random number
                printf("Your guess it too low. You have %d guesses left.\n", MAX_NUMBER - counter);
            } else {   // Case if the user input is bigger than random number
                printf("Your guess it too high. You have %d guesses left.\n", MAX_NUMBER - counter);
            }
        } else {   // Case if user input is invalid
            printf("Wrong format. Only numbers between (inclusive) 1 and 100 accepted.\n");
        } //
    } while(guess != random && counter < MAX_NUMBER);

    // Prints the message if the user reached allowed number of guesses
    if (counter == MAX_NUMBER) {
        printf("You're out of guesses.\n\n");
    }
}