// (C) Emma Litvin, Nicole Quinstedt. Group: 11 (2023)
// Work package 1
// Exercise 3
// Submission code: XXXX

/*------------------------------------------------------------------------------------------
References:
 - Stephen G. Kochan, Programming in C, 4th Edition
-------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------
Exercise 3: Computer creates a random integer number within a range from 1 to 100.
 Program asks the user to enter number. The program keep running and responds to user input
 in two different ways:
 1. if the user guessed the number correctly, the program confirms that the number was
    guessed correctly and prints number of attempts it took to guess the number, or
 2. informs the user if the guess was too low or too high.
 If the user provided the wrong guess, the program will continue running until number of
 guesses exceeds the value of MAX_NUMBER.
-------------------------------------------------------------------------------------------*/

// Include section
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// Define section
#define MAX_NUMBER 13

// Main program section
int main(void) {

    // Variables declaration
    int number,          // Number entered by the user
        lower = 1,       // Lower range for generating random number
        upper = 100,     // Upper limit for generating random number
        random,          // Random number generated by the program
        i,               // Used to run the for loop
        counter = 1;     // Number of guesses starting from 1

    /* Gives a random function a new seed (i.e., a starting point),
        where time(0) give the time in seconds since the Unix epoch. */
    srand(time(0));

    // Program creates random number between 1 and 100
    random = (rand() % (upper - lower + 1)) + lower;

    // Program runs until number of guesses reached MAX_NUMBER
    for(i = 1; i <= MAX_NUMBER; ++i){

        // Print message to prompt the user to input a number
        printf("Guess the number between 1 and 100: ");

        // Save provided user input into variable 'number'
        scanf("%i", &number);

        // Program compares the user input to generated random number
        if(number == random) {          // Case if number was guessed correctly
            printf("Your guess is correct! You have guessed %i times", counter);
            // Exits the loop
            break;
        } else if (number < random) {   // Case if the user input is smaller than random number
            // Program counts the guesses
            ++counter;
            printf("Your guess it too low. Try again.\n");
        } else {                        // Case if the user input is bigger than random number
            // Program counts the guesses
            ++counter;
            printf("Your guess it too high. Try again.\n");
        }
    }

    return 0;
}